app = "meiser-yt-backend"  # Change this to your Fly app name

kill_signal = "SIGINT"
kill_timeout = 5

[env]
PORT = "5000"

[build]
  image = "Dockerfile"

[deploy]
  release_command = ""

[[services]]
  internal_port = 5000
  protocol = "tcp"

  [[services.ports]]
    port = 80

  [[services.ports]]
    port = 443

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000
    grace_period = "5s"
    restart_limit = 0
